#!/usr/bin/env bash

parent_dirs=(
    "${HOME}/Repos"
)

child_dirs=(
    "${HOME}/.config/tmux"
    "${HOME}/.config/nvim"
)

export PARENT_WORKSPACES=$(find "${parent_dirs[@]}" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
export CHILD_WORKSPACES=$(find "${child_dirs[@]}" -mindepth 0 -maxdepth 0 -type d 2>/dev/null)

